### Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49

In [2]:
import numpy as np
v = np.arange(10,49)
print("Original vector:")
print(v)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


 ### Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
  
print ("Input  array : \n", arr)
    
out_tpl = np.nonzero(arr)
print ("Indices of non zero elements : ", out_tpl) 

Input  array : 
 [1 2 0 0 4 0]
Indices of non zero elements :  (array([0, 1, 4], dtype=int64),)


  ### Create a 10x10 array with random values and find the minimum and maximum values.

In [8]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.7628395  0.0309641  0.61058834 0.43251834 0.75407973 0.30263459
  0.97916366 0.11127641 0.4839363  0.42568618]
 [0.31170414 0.41273365 0.00868977 0.37524678 0.43531963 0.70111058
  0.7831546  0.54852612 0.04586353 0.6123872 ]
 [0.92243883 0.48591259 0.12185178 0.2055786  0.83896041 0.47055523
  0.28249495 0.50971156 0.99530879 0.22448468]
 [0.69781268 0.83114107 0.10940837 0.72184176 0.24553936 0.49466493
  0.16263965 0.43152947 0.19081697 0.25745509]
 [0.25707418 0.70261852 0.20190738 0.67532962 0.47929239 0.22646237
  0.05441721 0.26732842 0.50958003 0.09872714]
 [0.10294128 0.08844485 0.54499401 0.23495336 0.63816859 0.73665237
  0.13510603 0.34064943 0.4060055  0.39930201]
 [0.22442981 0.38177744 0.97061083 0.82560741 0.55557795 0.17806959
  0.38958104 0.35392282 0.14934731 0.19454393]
 [0.35489425 0.48265214 0.04687917 0.5561765  0.88252725 0.04346906
  0.13736285 0.54078449 0.74131256 0.58651222]
 [0.34938783 0.21695504 0.84325525 0.39167273 0.75647389 0.92847

### Create a random vector of size 30 and find the mean value.

In [10]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.mean()
print("Mean value :")
print(x)

Original array:
[0.11478418 0.87914079 0.87335401 0.06457485 0.36451719 0.30845263
 0.72438432 0.9314666  0.34649221 0.88693354]
Mean value :
[0.11478418 0.87914079 0.87335401 0.06457485 0.36451719 0.30845263
 0.72438432 0.9314666  0.34649221 0.88693354]
